# Site settings
title: Pizzeria Valdiano
email: pizza_guy@pizza.com
description: > # this means to ignore newlines until "baseurl:"

  Pizzeria Valdiano is an authentic pizzeria that creates a neighborhood New York-style feel with a family-friendly atmosphere that is commonplace in Southern Italy.
baseurl: "/pizzeria-3" # the subpath of your site, e.g. /blog/
url: "http://pizzeriavaldiano.com/" # the base hostname & protocol for your site
twitter_username: ValdianoPizza
facebook_username:  PizzeriaValdiano

# Build settings
markdown: kramdown
